### PR TITLE
Attempt osx-arm64

### PR DESCRIPTION
**Pull request by whophil**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Attempt osx-arm64 build.

### CODE REVIEW

**Comment by whophil** [comment]
I _think_ this works? I mostly followed along the instructions here: https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/

If I understand correctly, all arm64 builds are cross-compiled on Intel Macs. And because the build produces arm64 binaries, the build machine can't actually run tests.

**Comment by whophil** [comment]
Here is the testflo output for the osx-arm64 build, Python 3.10. There is one failure in an SLSQP test. Perhaps relaxing the tolerance on the test would be sufficient.

<details>

```
(pyoptsparse) philchiu@m1-mbp pyoptsparse % testflo --verbose .
/Users/philchiu/mambaforge/envs/pyoptsparse/lib/python3.10/site-packages/pyoptsparse/pyOpt_MPI.py:68: UserWarning: mpi4py could not be imported. mpi4py is required to use the parallel gradient analysis and parallel objective analysis for non-gradient based optimizers. Continuing using a dummy MPI module from pyOptSparse.
  warnings.warn(warn)
/Users/philchiu/mambaforge/envs/pyoptsparse/lib/python3.10/site-packages/pyoptsparse/pyOpt_MPI.py:68: UserWarning: mpi4py could not be imported. mpi4py is required to use the parallel gradient analysis and parallel objective analysis for non-gradient based optimizers. Continuing using a dummy MPI module from pyOptSparse.
  warnings.warn(warn)
/Users/philchiu/mambaforge/envs/pyoptsparse/lib/python3.10/site-packages/pyoptsparse/pyOpt_MPI.py:68: UserWarning: mpi4py could not be imported. mpi4py is required to use the parallel gradient analysis and parallel objective analysis for non-gradient based optimizers. Continuing using a dummy MPI module from pyOptSparse.
  warnings.warn(warn)
/Users/philchiu/mambaforge/envs/pyoptsparse/lib/python3.10/site-packages/pyoptsparse/pyOpt_MPI.py:68: UserWarning: mpi4py could not be imported. mpi4py is required to use the parallel gradient analysis and parallel objective analysis for non-gradient based optimizers. Continuing using a dummy MPI module from pyOptSparse.
  warnings.warn(warn)
/Users/philchiu/mambaforge/envs/pyoptsparse/lib/python3.10/site-packages/pyoptsparse/pyOpt_MPI.py:68: UserWarning: mpi4py could not be imported. mpi4py is required to use the parallel gradient analysis and parallel objective analysis for non-gradient based optimizers. Continuing using a dummy MPI module from pyOptSparse.
  warnings.warn(warn)
./tests/test_snopt_user_termination.py:TestUserTerminationStatus.test_sens ... SKIP (00:00:0.00, 53 MB)
Optimizer not available: SNOPT
/Users/philchiu/mambaforge/envs/pyoptsparse/lib/python3.10/site-packages/pyoptsparse/pyOpt_MPI.py:68: UserWarning: mpi4py could not be imported. mpi4py is required to use the parallel gradient analysis and parallel objective analysis for non-gradient based optimizers. Continuing using a dummy MPI module from pyOptSparse.
  warnings.warn(warn)
./tests/test_snopt_user_termination.py:TestUserTerminationStatus.test_obj ... SKIP (00:00:0.00, 53 MB)
Optimizer not available: SNOPT
/Users/philchiu/mambaforge/envs/pyoptsparse/lib/python3.10/site-packages/pyoptsparse/pyOpt_MPI.py:68: UserWarning: mpi4py could not be imported. mpi4py is required to use the parallel gradient analysis and parallel objective analysis for non-gradient based optimizers. Continuing using a dummy MPI module from pyOptSparse.
  warnings.warn(warn)
./tests/test_optProb.py:TestOptProb.test_finalize ... OK (00:00:0.01, 54 MB)
/Users/philchiu/mambaforge/envs/pyoptsparse/lib/python3.10/site-packages/pyoptsparse/pyOpt_MPI.py:68: UserWarning: mpi4py could not be imported. mpi4py is required to use the parallel gradient analysis and parallel objective analysis for non-gradient based optimizers. Continuing using a dummy MPI module from pyOptSparse.
  warnings.warn(warn)
./tests/test_rosenbrock.py:TestRosenbrock.test_optimization_4_NLPQLP ... SKIP (00:00:0.00, 54 MB)
('Optimizer not available: ', 'NLPQLP')
./tests/test_rosenbrock.py:TestRosenbrock.test_optimization_5_ParOpt ... SKIP (00:00:0.00, 54 MB)
('Optimizer not available: ', 'ParOpt')
./tests/test_rosenbrock.py:TestRosenbrock.test_snopt ... SKIP (00:00:0.00, 54 MB)
('Optimizer not available: ', 'SNOPT')
./tests/test_optProb.py:TestOptProb.test_mappings ... OK (00:00:0.04, 54 MB)
./tests/test_rosenbrock.py:TestRosenbrock.test_snopt_hotstart_starting_from_grad ... SKIP (00:00:0.00, 54 MB)
('Optimizer not available: ', 'SNOPT')
./tests/test_hs071.py:TestHS71.test_nlpqlp_informs ... SKIP (00:00:0.00, 54 MB)
('Optimizer not available: ', 'NLPQLP')
./tests/test_hs071.py:TestHS71.test_optimization_0_SNOPT ... SKIP (00:00:0.00, 54 MB)
('Optimizer not available: ', 'SNOPT')
/Users/philchiu/mambaforge/envs/pyoptsparse/lib/python3.10/site-packages/pyoptsparse/pyOpt_MPI.py:68: UserWarning: mpi4py could not be imported. mpi4py is required to use the parallel gradient analysis and parallel objective analysis for non-gradient based optimizers. Continuing using a dummy MPI module from pyOptSparse.
  warnings.warn(warn)
./tests/test_optProb.py:TestOptProb.test_setDV_getDV ... OK (00:00:0.01, 54 MB)
./tests/test_hs071.py:TestHS71.test_ipopt_informs ... OK (00:00:0.01, 58 MB)
./tests/test_optProb.py:TestOptProb.test_setDV_VarGroup ... OK (00:00:0.02, 54 MB)
./tests/test_hs071.py:TestHS71.test_optimization_2_SLSQP ... OK (00:00:0.00, 54 MB)
./tests/test_hs071.py:TestHS71.test_optimization_5_NLPQLP ... SKIP (00:00:0.00, 54 MB)
('Optimizer not available: ', 'NLPQLP')
./tests/test_hs071.py:TestHS71.test_optimization_3_PSQP ... OK (00:00:0.00, 58 MB)
./tests/test_hs071.py:TestHS71.test_optimization_6_ParOpt ... SKIP (00:00:0.00, 54 MB)
('Optimizer not available: ', 'ParOpt')
./tests/test_hs071.py:TestHS71.test_psqp_informs ... OK (00:00:0.00, 58 MB)
./tests/test_hs071.py:TestHS71.test_slsqp_informs ... OK (00:00:0.00, 54 MB)
./tests/test_hs071.py:TestHS71.test_optimization_1_IPOPT ... OK (00:00:0.02, 58 MB)
./tests/test_hs071.py:TestHS71.test_snopt_informs ... SKIP (00:00:0.00, 58 MB)
('Optimizer not available: ', 'SNOPT')
./tests/test_hs071.py:TestHS71.test_snopt_setDVFromHist ... SKIP (00:00:0.00, 58 MB)
('Optimizer not available: ', 'SNOPT')
./tests/test_snopt_bugfix.py:TestSNOPTBug.test_opt ... SKIP (00:00:0.00, 58 MB)
Optimizer not available: SNOPT
./tests/test_snopt_bugfix.py:TestSNOPTBug.test_opt_bug1 ... SKIP (00:00:0.00, 58 MB)
Optimizer not available: SNOPT
./tests/test_snopt_bugfix.py:TestSNOPTBug.test_opt_bug_print_2con ... SKIP (00:00:0.00, 58 MB)
Optimizer not available: SNOPT
./tests/test_hs071.py:TestHS71.test_optimization_4_CONMIN ... OK (00:00:0.01, 55 MB)
./tests/test_hs015.py:TestHS15.test_optimization_0_SLSQP ... FAIL (00:00:0.00, 55 MB)
Traceback (most recent call last):
  File "/Users/philchiu/mambaforge/envs/pyoptsparse/lib/python3.10/site-packages/testflo/test.py", line 477, in _try_call
    func()
  File "/Users/philchiu/mambaforge/envs/pyoptsparse/lib/python3.10/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/Users/philchiu/repos/pyoptsparse/./tests/test_hs015.py", line 128, in test_optimization
    self.assert_solution_allclose(sol, self.tol[optName])
  File "/Users/philchiu/repos/pyoptsparse/./tests/testing_utils.py", line 194, in assert_solution_allclose
    assert_allclose(sol_objectives, self.fStar[self.sol_index], atol=tol, rtol=tol)
  File "/Users/philchiu/mambaforge/envs/pyoptsparse/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/Users/philchiu/mambaforge/envs/pyoptsparse/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-08, atol=1e-08

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 0.0006391
Max relative difference: 2.08516973e-06
 x: array([306.499361])
 y: array(306.5)

./tests/test_hs015.py:TestHS15.test_optimization_1_PSQP ... OK (00:00:0.00, 55 MB)
./tests/test_hs015.py:TestHS15.test_optimization_2_CONMIN ... OK (00:00:0.00, 55 MB)
./tests/test_hs015.py:TestHS15.test_optimization_3_NLPQLP ... SKIP (00:00:0.00, 55 MB)
('Optimizer not available: ', 'NLPQLP')
./tests/test_hs015.py:TestHS15.test_optimization_4_ParOpt ... SKIP (00:00:0.00, 55 MB)
('Optimizer not available: ', 'ParOpt')
./tests/test_hs015.py:TestHS15.test_snopt ... SKIP (00:00:0.00, 55 MB)
('Optimizer not available: ', 'SNOPT')
./tests/test_hs015.py:TestHS15.test_snopt_hotstart ... SKIP (00:00:0.00, 55 MB)
('Optimizer not available: ', 'SNOPT')
./tests/test_hs015.py:TestHS15.test_snopt_snstop ... SKIP (00:00:0.00, 55 MB)
('Optimizer not available: ', 'SNOPT')
./tests/test_hs071.py:TestHS71.test_slsqp_setDV ... OK (00:00:0.26, 57 MB)
./tests/test_hs071.py:TestHS71.test_slsqp_scaling_offset_optProb ... OK (00:00:0.28, 61 MB)
./tests/test_hs015.py:TestHS15.test_ipopt ... OK (00:00:0.37, 62 MB)
./tests/test_tp109.py:TestTP109.test_slsqp ... OK (00:00:0.02, 62 MB)
./tests/test_tp109.py:TestTP109.test_snopt ... SKIP (00:00:0.00, 62 MB)
('Optimizer not available: ', 'SNOPT')
./tests/test_large_sparse.py:TestLarge.test_dense_workspace_too_small ... SKIP (00:00:0.01, 64 MB)
('Optimizer not available: ', 'SNOPT')
./tests/test_large_sparse.py:TestLarge.test_opt_0_SNOPT ... SKIP (00:00:0.14, 79 MB)
('Optimizer not available: ', 'SNOPT')
./tests/test_rosenbrock.py:TestRosenbrock.test_optimization_2_PSQP ... OK (00:00:1.04, 59 MB)
./tests/test_large_sparse.py:TestLarge.test_opt_2_SNOPT ... SKIP (00:00:0.01, 61 MB)
('Optimizer not available: ', 'SNOPT')
./tests/test_require_mpi_env_var.py:TestRequireMPIEnvVar.test_do_not_use_mpi ... OK (00:00:0.00, 61 MB)
./tests/test_require_mpi_env_var.py:TestRequireMPIEnvVar.test_no_mpi_requirement_given ... OK (00:00:0.00, 61 MB)
./tests/test_require_mpi_env_var.py:TestRequireMPIEnvVar.test_require_mpi ... SKIP (00:00:0.00, 61 MB)
mpi4py not available, skipping test.
./tests/test_require_mpi_env_var.py:TestRequireMPIEnvVarOnParOpt.test_do_not_use_mpi_check_paropt ... SKIP (00:00:0.00, 61 MB)
('Optimizer not available:', 'paropt')
./tests/test_require_mpi_env_var.py:TestRequireMPIEnvVarOnParOpt.test_no_mpi_requirement_given_check_paropt ... SKIP (00:00:0.00, 61 MB)
('Optimizer not available:', 'paropt')
./tests/test_require_mpi_env_var.py:TestRequireMPIEnvVarOnParOpt.test_require_mpi_check_paropt ... SKIP (00:00:0.00, 61 MB)
('Optimizer not available:', 'paropt')
./tests/test_nsga2_multi_objective.py:TestNSGA2.test_opt ... OK (00:00:1.31, 67 MB)
./tests/test_rosenbrock.py:TestRosenbrock.test_optimization_1_SLSQP ... OK (00:00:1.60, 59 MB)
./tests/test_rosenbrock.py:TestRosenbrock.test_optimization_3_CONMIN ... OK (00:00:3.03, 60 MB)
./tests/test_rosenbrock.py:TestRosenbrock.test_optimization_0_IPOPT ... OK (00:00:4.68, 65 MB)
./tests/test_tp109.py:TestTP109.test_autorefine ... SKIP (00:00:5.67, 62 MB)
('Optimizer not available: ', 'SNOPT')
./tests/test_large_sparse.py:TestLarge.test_opt_1_IPOPT ... OK (00:00:6.81, 251 MB)
./tests/test_sphere.py:TestSphere.test_optimization_0_ALPSO ... OK (00:00:20.49, 65 MB)


The following tests were skipped:
test_hs015.py:TestHS15.test_optimization_3_NLPQLP
test_hs015.py:TestHS15.test_optimization_4_ParOpt
test_hs015.py:TestHS15.test_snopt
test_hs015.py:TestHS15.test_snopt_hotstart
test_hs015.py:TestHS15.test_snopt_snstop
test_hs071.py:TestHS71.test_nlpqlp_informs
test_hs071.py:TestHS71.test_optimization_0_SNOPT
test_hs071.py:TestHS71.test_optimization_5_NLPQLP
test_hs071.py:TestHS71.test_optimization_6_ParOpt
test_hs071.py:TestHS71.test_snopt_informs
test_hs071.py:TestHS71.test_snopt_setDVFromHist
test_large_sparse.py:TestLarge.test_dense_workspace_too_small
test_large_sparse.py:TestLarge.test_opt_0_SNOPT
test_large_sparse.py:TestLarge.test_opt_2_SNOPT
test_require_mpi_env_var.py:TestRequireMPIEnvVar.test_require_mpi
test_require_mpi_env_var.py:TestRequireMPIEnvVarOnParOpt.test_do_not_use_mpi_check_paropt
test_require_mpi_env_var.py:TestRequireMPIEnvVarOnParOpt.test_no_mpi_requirement_given_check_paropt
test_require_mpi_env_var.py:TestRequireMPIEnvVarOnParOpt.test_require_mpi_check_paropt
test_rosenbrock.py:TestRosenbrock.test_optimization_4_NLPQLP
test_rosenbrock.py:TestRosenbrock.test_optimization_5_ParOpt
test_rosenbrock.py:TestRosenbrock.test_snopt
test_rosenbrock.py:TestRosenbrock.test_snopt_hotstart_starting_from_grad
test_snopt_bugfix.py:TestSNOPTBug.test_opt
test_snopt_bugfix.py:TestSNOPTBug.test_opt_bug1
test_snopt_bugfix.py:TestSNOPTBug.test_opt_bug_print_2con
test_snopt_user_termination.py:TestUserTerminationStatus.test_obj
test_snopt_user_termination.py:TestUserTerminationStatus.test_sens
test_tp109.py:TestTP109.test_autorefine
test_tp109.py:TestTP109.test_snopt


The following tests failed:
test_hs015.py:TestHS15.test_optimization_0_SLSQP


Passed:  26
Failed:  1
Skipped: 29


Ran 56 tests using 8 processes
Wall clock time:   00:00:20.91
```
</details>

**Comment by nwu63** [comment]
Instead of loosening the tolerance, maybe we just need to set a tighter `ACC` value for SLSQP so that it converges better. In any case, would you prefer bumping stuff upstream then waiting for all tests to pass, or just releasing this as-is and patch it separately?

**Comment by whophil** [comment]
I am OK with merging this as-is, as it's only the test which is failing for tolerance issues. If you don't have osx arm64 hardware I can help out with the upstream part.

Aside from the tolerance issues, there is a pesky issue where the `osx_64_numpy1.19python3.8.____cpython` build fails, seemingly intermittently, due to a missing `.out` file from another SLSQP test. I will re-run again and see if it solves itself...

**Comment by whophil** [comment]
The builds are passing because osx-arm64 isn't actually tested on CI. (On conda-forge, osx-arm64 builds are cross compiled on Intel Macs for now, so they can't actually run the built packages).  The tolerance error that I pasted above is from local testing on my M1 machine (using a built package I downloaded from CI as an artifact).

**Comment by nwu63** [comment]
Ah I see, I'll merge this then.

**Pull request merged**
