### PR TITLE
disabled pypy build

### PR DESCRIPTION
**Pull request by nwu63**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Trying this again after `master` was updated. Basically same as #5.

### CODE REVIEW

**Comment by nwu63** [comment]
@conda-forge-admin, please rerender

**Comment by marcomangano** [comment]
There is a duplicate `ipopt` that needs to be removed, see the diff in `recipe/meta.yaml` in  #5

**Comment by nwu63** [comment]
@conda-forge-admin, please rerender

**Comment by whophil** [comment]
@nwu63 did you ever find out why the builds on #5 were hanging?

**Comment by nwu63** [comment]
I've absolutely no idea :/

**Pull request merged**
